#!/bin/sh
while read file
do
    case "$1" in
        "x")
            image_index=$(expr `ls ~/media/images/toffee/ | cut -d "e" -f2 | sort -n | tail -1` + 1)
            mv "$file" "/home/$USER/media/images/toffee/image$image_index"
            ;;
        "y")
            echo $file | tr -d "\n" | xclip -selection c
            notify-send "$file"
            ;;
        "w")
            hsetroot -fill "$file"
            #wal -i "$file"
            #cp "$file" ~/.cache/wallpaper
            #/usr/bin/pywal_awesome_colors.sh
            #/usr/bin/dunst_pywal.sh
            #sudo oomoxify-cli -s /usr/share/spotify/spotify-client/Apps -g /home/mahmooz/.cache/wal/colors-oomox
            #sed -i '/SchemeUrg/d' ~/.cache/wal/colors-wal-dwm.h
            #sudo make install clean -C ~/workspace/dwm
            #notify-send "wallpaper colors generated"
            ;;
        "a")
            mv "$file" ~/media/images/wal/ignore/
            ;;
        "d")
            rm "$file"
            ;;
        "s")
            mv "$file" ~/media/images/wal/
            ;;
        "r")
            mv "$file" `echo $file | dmenu -it "$file"`
            ;;
        "y")
            echo "$file" | xclip -selection c
            ;;
    esac
done
