#!/bin/sh
while read file
do
    case "$1" in
        "w")
            hsetroot -fill "$file"
            ;;
        "a")
            mv "$file" ~/pictures/ignore
            ;;
        "d")
            rm "$file"
            ;;
        "s")
            mv "$file" ~/pictures
            ;;
        "r")
            mv "$file" `echo $file | dmenu -it "$file"`
            ;;
    esac
done
