#!/bin/sh

bspc config border_width        1
bspc config window_gap          1
bspc config top_padding         35
bspc config bottom_padding      35

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

bspc monitor --reset-desktops code music web term etc etc2

bspwm_sxhkd.sh &
