#!/bin/sh

bspc config border_width        3
bspc config window_gap          1
bspc config top_padding         20

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

bspc monitor --reset-desktops code music web term etc etc2

bspwm_sxhkd.sh &
lemonbar.sh | lemonbar -p -f "inconsolata-11" &

screen_size=$(xrandr | grep primary | cut -d ' ' -f4 | cut -d '+' -f1)
bspc subscribe node_geometry | while read a b c d geometry; do
    echo $geometry | grep $screen_size && pkill lemonbar || \
    pgrep lemonbar > /dev/null || lemonbar.sh | lemonbar -p -f "inconsolata-11" &
done &
